services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Parameters
  parameters:
    telephonedirectory.email_service.settings:
      pidOfDetailPage: 123

  JWeiland\Telephonedirectory\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  # Will be instanciated by GU::makeInstance in SendMailToEmployeeTask
  JWeiland\Telephonedirectory\Service\EmailService:
    public: true
    arguments:
      $settings: '%telephonedirectory.email_service.settings%'

  # EventListeners
  JWeiland\Telephonedirectory\EventListener\AddPaginatorEventListener:
    tags:
      - name: event.listener
        event: JWeiland\Telephonedirectory\Event\PostProcessFluidVariablesEvent
  JWeiland\Telephonedirectory\EventListener\AddGlossaryEventListener:
    tags:
      - name: event.listener
        event: JWeiland\Telephonedirectory\Event\PostProcessFluidVariablesEvent
        after: JWeiland\Telephonedirectory\EventListener\AddPaginatorEventListener

  # Will be instanciated by GU::makeInstance in SendMailToEmployeeTask
  JWeiland\Telephonedirectory\Repository\EmployeeFactory:
    public: true;
    arguments: [!tagged_iterator {tag: 'telephonedirectory.add_record_to_employee'}]

  JWeiland\Telephonedirectory\Repository\Handler\AddAdditionalFunctionsToEmployee:
    tags:
      - name: 'telephonedirectory.add_record_to_employee'
  JWeiland\Telephonedirectory\Repository\Handler\AddBuildingToEmployee:
    tags:
      - name: 'telephonedirectory.add_record_to_employee'
  JWeiland\Telephonedirectory\Repository\Handler\AddDepartmentToEmployee:
    tags:
      - name: 'telephonedirectory.add_record_to_employee'
  JWeiland\Telephonedirectory\Repository\Handler\AddLanguageSkillsToEmployee:
    tags:
      - name: 'telephonedirectory.add_record_to_employee'
  JWeiland\Telephonedirectory\Repository\Handler\AddOfficeToEmployee:
    tags:
      - name: 'telephonedirectory.add_record_to_employee'
  JWeiland\Telephonedirectory\Repository\Handler\AddSubjectFieldToEmployee:
    tags:
      - name: 'telephonedirectory.add_record_to_employee'
